//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.269.
// 
#pragma warning disable 1591

namespace ConsumirSSD.wscorporativo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EncabezadoDoccumentosSSDSoap", Namespace="http://tempuri.org/")]
    public partial class EncabezadoDoccumentosSSD : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback encabezadoDoctosSSDOperationCompleted;
        
        private System.Threading.SendOrPostCallback documentosAdjuntosSSDOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarProcesoSSDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EncabezadoDoccumentosSSD() {
            this.Url = global::ConsumirSSD.Properties.Settings.Default.ConsumirSSD_cl_sdit_wscorporativo_EncabezadoDoccumentosSSD;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event encabezadoDoctosSSDCompletedEventHandler encabezadoDoctosSSDCompleted;
        
        /// <remarks/>
        public event documentosAdjuntosSSDCompletedEventHandler documentosAdjuntosSSDCompleted;
        
        /// <remarks/>
        public event insertarProcesoSSDCompletedEventHandler insertarProcesoSSDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/encabezadoDoctosSSD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public encabezadoDoctos[] encabezadoDoctosSSD(int NroProceso) {
            object[] results = this.Invoke("encabezadoDoctosSSD", new object[] {
                        NroProceso});
            return ((encabezadoDoctos[])(results[0]));
        }
        
        /// <remarks/>
        public void encabezadoDoctosSSDAsync(int NroProceso) {
            this.encabezadoDoctosSSDAsync(NroProceso, null);
        }
        
        /// <remarks/>
        public void encabezadoDoctosSSDAsync(int NroProceso, object userState) {
            if ((this.encabezadoDoctosSSDOperationCompleted == null)) {
                this.encabezadoDoctosSSDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnencabezadoDoctosSSDOperationCompleted);
            }
            this.InvokeAsync("encabezadoDoctosSSD", new object[] {
                        NroProceso}, this.encabezadoDoctosSSDOperationCompleted, userState);
        }
        
        private void OnencabezadoDoctosSSDOperationCompleted(object arg) {
            if ((this.encabezadoDoctosSSDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.encabezadoDoctosSSDCompleted(this, new encabezadoDoctosSSDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/documentosAdjuntosSSD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public datosDoctos[] documentosAdjuntosSSD(int NroProceso) {
            object[] results = this.Invoke("documentosAdjuntosSSD", new object[] {
                        NroProceso});
            return ((datosDoctos[])(results[0]));
        }
        
        /// <remarks/>
        public void documentosAdjuntosSSDAsync(int NroProceso) {
            this.documentosAdjuntosSSDAsync(NroProceso, null);
        }
        
        /// <remarks/>
        public void documentosAdjuntosSSDAsync(int NroProceso, object userState) {
            if ((this.documentosAdjuntosSSDOperationCompleted == null)) {
                this.documentosAdjuntosSSDOperationCompleted = new System.Threading.SendOrPostCallback(this.OndocumentosAdjuntosSSDOperationCompleted);
            }
            this.InvokeAsync("documentosAdjuntosSSD", new object[] {
                        NroProceso}, this.documentosAdjuntosSSDOperationCompleted, userState);
        }
        
        private void OndocumentosAdjuntosSSDOperationCompleted(object arg) {
            if ((this.documentosAdjuntosSSDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.documentosAdjuntosSSDCompleted(this, new documentosAdjuntosSSDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertarProcesoSSD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ingresarDocto[] insertarProcesoSSD(
                    string CODIGO_SERVICIO_SOLICITANTE, 
                    int CODIGO_TIPO_DOCUMENTO, 
                    int CODIGO_ACCION, 
                    int REGION_ORIGEN_DOCUMENTO, 
                    int ANNO_DOCUMENTO, 
                    string FECHA_DOCUMENTO, 
                    string CODIGO_ORIGEN, 
                    string MATERIA_DOCUMENTO, 
                    string CODIGO_DESTINO, 
                    int NRO_INTERNO_DOCUMENTO, 
                    string TRAMITE_DOCUMENTO, 
                    string CORREO_USUARIO, 
                    string NOMBRE_FUNCIONARIO, 
                    string OBSERVACIONES_DOCUMENTO, 
                    int PLAZO_DOCUMENTO, 
                    string DATOS_ADICIONALES_REMITENTE, 
                    string DATOS_ADICIONALES_DESTINO, 
                    int REFERENCIA, 
                    string CODIGO_TIPO_DOCUMENTO_) {
            object[] results = this.Invoke("insertarProcesoSSD", new object[] {
                        CODIGO_SERVICIO_SOLICITANTE,
                        CODIGO_TIPO_DOCUMENTO,
                        CODIGO_ACCION,
                        REGION_ORIGEN_DOCUMENTO,
                        ANNO_DOCUMENTO,
                        FECHA_DOCUMENTO,
                        CODIGO_ORIGEN,
                        MATERIA_DOCUMENTO,
                        CODIGO_DESTINO,
                        NRO_INTERNO_DOCUMENTO,
                        TRAMITE_DOCUMENTO,
                        CORREO_USUARIO,
                        NOMBRE_FUNCIONARIO,
                        OBSERVACIONES_DOCUMENTO,
                        PLAZO_DOCUMENTO,
                        DATOS_ADICIONALES_REMITENTE,
                        DATOS_ADICIONALES_DESTINO,
                        REFERENCIA,
                        CODIGO_TIPO_DOCUMENTO_});
            return ((ingresarDocto[])(results[0]));
        }
        
        /// <remarks/>
        public void insertarProcesoSSDAsync(
                    string CODIGO_SERVICIO_SOLICITANTE, 
                    int CODIGO_TIPO_DOCUMENTO, 
                    int CODIGO_ACCION, 
                    int REGION_ORIGEN_DOCUMENTO, 
                    int ANNO_DOCUMENTO, 
                    string FECHA_DOCUMENTO, 
                    string CODIGO_ORIGEN, 
                    string MATERIA_DOCUMENTO, 
                    string CODIGO_DESTINO, 
                    int NRO_INTERNO_DOCUMENTO, 
                    string TRAMITE_DOCUMENTO, 
                    string CORREO_USUARIO, 
                    string NOMBRE_FUNCIONARIO, 
                    string OBSERVACIONES_DOCUMENTO, 
                    int PLAZO_DOCUMENTO, 
                    string DATOS_ADICIONALES_REMITENTE, 
                    string DATOS_ADICIONALES_DESTINO, 
                    int REFERENCIA, 
                    string CODIGO_TIPO_DOCUMENTO_) {
            this.insertarProcesoSSDAsync(CODIGO_SERVICIO_SOLICITANTE, CODIGO_TIPO_DOCUMENTO, CODIGO_ACCION, REGION_ORIGEN_DOCUMENTO, ANNO_DOCUMENTO, FECHA_DOCUMENTO, CODIGO_ORIGEN, MATERIA_DOCUMENTO, CODIGO_DESTINO, NRO_INTERNO_DOCUMENTO, TRAMITE_DOCUMENTO, CORREO_USUARIO, NOMBRE_FUNCIONARIO, OBSERVACIONES_DOCUMENTO, PLAZO_DOCUMENTO, DATOS_ADICIONALES_REMITENTE, DATOS_ADICIONALES_DESTINO, REFERENCIA, CODIGO_TIPO_DOCUMENTO_, null);
        }
        
        /// <remarks/>
        public void insertarProcesoSSDAsync(
                    string CODIGO_SERVICIO_SOLICITANTE, 
                    int CODIGO_TIPO_DOCUMENTO, 
                    int CODIGO_ACCION, 
                    int REGION_ORIGEN_DOCUMENTO, 
                    int ANNO_DOCUMENTO, 
                    string FECHA_DOCUMENTO, 
                    string CODIGO_ORIGEN, 
                    string MATERIA_DOCUMENTO, 
                    string CODIGO_DESTINO, 
                    int NRO_INTERNO_DOCUMENTO, 
                    string TRAMITE_DOCUMENTO, 
                    string CORREO_USUARIO, 
                    string NOMBRE_FUNCIONARIO, 
                    string OBSERVACIONES_DOCUMENTO, 
                    int PLAZO_DOCUMENTO, 
                    string DATOS_ADICIONALES_REMITENTE, 
                    string DATOS_ADICIONALES_DESTINO, 
                    int REFERENCIA, 
                    string CODIGO_TIPO_DOCUMENTO_, 
                    object userState) {
            if ((this.insertarProcesoSSDOperationCompleted == null)) {
                this.insertarProcesoSSDOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarProcesoSSDOperationCompleted);
            }
            this.InvokeAsync("insertarProcesoSSD", new object[] {
                        CODIGO_SERVICIO_SOLICITANTE,
                        CODIGO_TIPO_DOCUMENTO,
                        CODIGO_ACCION,
                        REGION_ORIGEN_DOCUMENTO,
                        ANNO_DOCUMENTO,
                        FECHA_DOCUMENTO,
                        CODIGO_ORIGEN,
                        MATERIA_DOCUMENTO,
                        CODIGO_DESTINO,
                        NRO_INTERNO_DOCUMENTO,
                        TRAMITE_DOCUMENTO,
                        CORREO_USUARIO,
                        NOMBRE_FUNCIONARIO,
                        OBSERVACIONES_DOCUMENTO,
                        PLAZO_DOCUMENTO,
                        DATOS_ADICIONALES_REMITENTE,
                        DATOS_ADICIONALES_DESTINO,
                        REFERENCIA,
                        CODIGO_TIPO_DOCUMENTO_}, this.insertarProcesoSSDOperationCompleted, userState);
        }
        
        private void OninsertarProcesoSSDOperationCompleted(object arg) {
            if ((this.insertarProcesoSSDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarProcesoSSDCompleted(this, new insertarProcesoSSDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class encabezadoDoctos {
        
        private string dOC_NRODOCField;
        
        private string dOC_FECHADOCField;
        
        private string dOC_COPIA_INFORMATIVAField;
        
        private string dOC_REGION_ORIGENField;
        
        private string dOC_USUARIOField;
        
        private string dOC_MATERIAField;
        
        private string dOC_IDENTField;
        
        private string dOCTRAMITEField;
        
        private string dOC_FUNCIONARIOField;
        
        private string dOC_NROINTERNOField;
        
        private string dOC_OBSField;
        
        private string sERVICIO_ORIGENField;
        
        private string dOC_PLAZOField;
        
        private string dOC_ESTADOField;
        
        private string dOC_DATOS_ADICIONALES_REMITENTField;
        
        private string dOC_DATOS_ADICIONALES_DESTINATField;
        
        private string dOC_PREPARADOField;
        
        private string cOD_GASTOField;
        
        private string dOP_NROOPField;
        
        private string dOP_ARCHIVADOField;
        
        private string dOP_FECHAINGField;
        
        private string dOP_FECHADESPField;
        
        private string dOP_TIPO_ORIGENField;
        
        private string dOP_HORADESPField;
        
        private string dOP_REFERENCIAField;
        
        private string dOP_REFERENCIA_2Field;
        
        private string dOP_HORAINGField;
        
        private string dOP_LOTESField;
        
        private string oRI_NOMBREField;
        
        private string dESTINOField;
        
        private string oRI_PRE_DESField;
        
        private string rEGIONField;
        
        private string aCC_DESCRIPCIONField;
        
        private string tDOC_DESCRIPField;
        
        /// <comentarios/>
        public string DOC_NRODOC {
            get {
                return this.dOC_NRODOCField;
            }
            set {
                this.dOC_NRODOCField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_FECHADOC {
            get {
                return this.dOC_FECHADOCField;
            }
            set {
                this.dOC_FECHADOCField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_COPIA_INFORMATIVA {
            get {
                return this.dOC_COPIA_INFORMATIVAField;
            }
            set {
                this.dOC_COPIA_INFORMATIVAField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_REGION_ORIGEN {
            get {
                return this.dOC_REGION_ORIGENField;
            }
            set {
                this.dOC_REGION_ORIGENField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_USUARIO {
            get {
                return this.dOC_USUARIOField;
            }
            set {
                this.dOC_USUARIOField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_MATERIA {
            get {
                return this.dOC_MATERIAField;
            }
            set {
                this.dOC_MATERIAField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_IDENT {
            get {
                return this.dOC_IDENTField;
            }
            set {
                this.dOC_IDENTField = value;
            }
        }
        
        /// <comentarios/>
        public string DOCTRAMITE {
            get {
                return this.dOCTRAMITEField;
            }
            set {
                this.dOCTRAMITEField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_FUNCIONARIO {
            get {
                return this.dOC_FUNCIONARIOField;
            }
            set {
                this.dOC_FUNCIONARIOField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_NROINTERNO {
            get {
                return this.dOC_NROINTERNOField;
            }
            set {
                this.dOC_NROINTERNOField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_OBS {
            get {
                return this.dOC_OBSField;
            }
            set {
                this.dOC_OBSField = value;
            }
        }
        
        /// <comentarios/>
        public string SERVICIO_ORIGEN {
            get {
                return this.sERVICIO_ORIGENField;
            }
            set {
                this.sERVICIO_ORIGENField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_PLAZO {
            get {
                return this.dOC_PLAZOField;
            }
            set {
                this.dOC_PLAZOField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_ESTADO {
            get {
                return this.dOC_ESTADOField;
            }
            set {
                this.dOC_ESTADOField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_DATOS_ADICIONALES_REMITENT {
            get {
                return this.dOC_DATOS_ADICIONALES_REMITENTField;
            }
            set {
                this.dOC_DATOS_ADICIONALES_REMITENTField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_DATOS_ADICIONALES_DESTINAT {
            get {
                return this.dOC_DATOS_ADICIONALES_DESTINATField;
            }
            set {
                this.dOC_DATOS_ADICIONALES_DESTINATField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_PREPARADO {
            get {
                return this.dOC_PREPARADOField;
            }
            set {
                this.dOC_PREPARADOField = value;
            }
        }
        
        /// <comentarios/>
        public string COD_GASTO {
            get {
                return this.cOD_GASTOField;
            }
            set {
                this.cOD_GASTOField = value;
            }
        }
        
        /// <comentarios/>
        public string DOP_NROOP {
            get {
                return this.dOP_NROOPField;
            }
            set {
                this.dOP_NROOPField = value;
            }
        }
        
        /// <comentarios/>
        public string DOP_ARCHIVADO {
            get {
                return this.dOP_ARCHIVADOField;
            }
            set {
                this.dOP_ARCHIVADOField = value;
            }
        }
        
        /// <comentarios/>
        public string DOP_FECHAING {
            get {
                return this.dOP_FECHAINGField;
            }
            set {
                this.dOP_FECHAINGField = value;
            }
        }
        
        /// <comentarios/>
        public string DOP_FECHADESP {
            get {
                return this.dOP_FECHADESPField;
            }
            set {
                this.dOP_FECHADESPField = value;
            }
        }
        
        /// <comentarios/>
        public string DOP_TIPO_ORIGEN {
            get {
                return this.dOP_TIPO_ORIGENField;
            }
            set {
                this.dOP_TIPO_ORIGENField = value;
            }
        }
        
        /// <comentarios/>
        public string DOP_HORADESP {
            get {
                return this.dOP_HORADESPField;
            }
            set {
                this.dOP_HORADESPField = value;
            }
        }
        
        /// <comentarios/>
        public string DOP_REFERENCIA {
            get {
                return this.dOP_REFERENCIAField;
            }
            set {
                this.dOP_REFERENCIAField = value;
            }
        }
        
        /// <comentarios/>
        public string DOP_REFERENCIA_2 {
            get {
                return this.dOP_REFERENCIA_2Field;
            }
            set {
                this.dOP_REFERENCIA_2Field = value;
            }
        }
        
        /// <comentarios/>
        public string DOP_HORAING {
            get {
                return this.dOP_HORAINGField;
            }
            set {
                this.dOP_HORAINGField = value;
            }
        }
        
        /// <comentarios/>
        public string DOP_LOTES {
            get {
                return this.dOP_LOTESField;
            }
            set {
                this.dOP_LOTESField = value;
            }
        }
        
        /// <comentarios/>
        public string ORI_NOMBRE {
            get {
                return this.oRI_NOMBREField;
            }
            set {
                this.oRI_NOMBREField = value;
            }
        }
        
        /// <comentarios/>
        public string DESTINO {
            get {
                return this.dESTINOField;
            }
            set {
                this.dESTINOField = value;
            }
        }
        
        /// <comentarios/>
        public string ORI_PRE_DES {
            get {
                return this.oRI_PRE_DESField;
            }
            set {
                this.oRI_PRE_DESField = value;
            }
        }
        
        /// <comentarios/>
        public string REGION {
            get {
                return this.rEGIONField;
            }
            set {
                this.rEGIONField = value;
            }
        }
        
        /// <comentarios/>
        public string ACC_DESCRIPCION {
            get {
                return this.aCC_DESCRIPCIONField;
            }
            set {
                this.aCC_DESCRIPCIONField = value;
            }
        }
        
        /// <comentarios/>
        public string TDOC_DESCRIP {
            get {
                return this.tDOC_DESCRIPField;
            }
            set {
                this.tDOC_DESCRIPField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ingresarDocto {
        
        private string sER_CODIGOField;
        
        private int tDOC_CODIGOField;
        
        private int aCC_CODIGOField;
        
        private int dOC_REGION_ORIGENField;
        
        private int dOC_ANODOCField;
        
        private string dOC_FECHADOCField;
        
        private string dOC_ORIGENField;
        
        private string dOC_MATERIAField;
        
        private string dOC_DESTINOField;
        
        private int dOC_NROINTERNOField;
        
        private string dOC_TRAMITEField;
        
        private string dOC_USUARIOField;
        
        private string dOC_FUNCIONARIOField;
        
        private string dOC_OBSField;
        
        private int dOC_PLAZOField;
        
        private string dOC_DATOS_ADIC_REMField;
        
        private string dOC_DATOS_ADIC_DESField;
        
        private int dOC_REFERENCIA_1Field;
        
        private string tIPOField;
        
        /// <comentarios/>
        public string SER_CODIGO {
            get {
                return this.sER_CODIGOField;
            }
            set {
                this.sER_CODIGOField = value;
            }
        }
        
        /// <comentarios/>
        public int TDOC_CODIGO {
            get {
                return this.tDOC_CODIGOField;
            }
            set {
                this.tDOC_CODIGOField = value;
            }
        }
        
        /// <comentarios/>
        public int ACC_CODIGO {
            get {
                return this.aCC_CODIGOField;
            }
            set {
                this.aCC_CODIGOField = value;
            }
        }
        
        /// <comentarios/>
        public int DOC_REGION_ORIGEN {
            get {
                return this.dOC_REGION_ORIGENField;
            }
            set {
                this.dOC_REGION_ORIGENField = value;
            }
        }
        
        /// <comentarios/>
        public int DOC_ANODOC {
            get {
                return this.dOC_ANODOCField;
            }
            set {
                this.dOC_ANODOCField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_FECHADOC {
            get {
                return this.dOC_FECHADOCField;
            }
            set {
                this.dOC_FECHADOCField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_ORIGEN {
            get {
                return this.dOC_ORIGENField;
            }
            set {
                this.dOC_ORIGENField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_MATERIA {
            get {
                return this.dOC_MATERIAField;
            }
            set {
                this.dOC_MATERIAField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_DESTINO {
            get {
                return this.dOC_DESTINOField;
            }
            set {
                this.dOC_DESTINOField = value;
            }
        }
        
        /// <comentarios/>
        public int DOC_NROINTERNO {
            get {
                return this.dOC_NROINTERNOField;
            }
            set {
                this.dOC_NROINTERNOField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_TRAMITE {
            get {
                return this.dOC_TRAMITEField;
            }
            set {
                this.dOC_TRAMITEField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_USUARIO {
            get {
                return this.dOC_USUARIOField;
            }
            set {
                this.dOC_USUARIOField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_FUNCIONARIO {
            get {
                return this.dOC_FUNCIONARIOField;
            }
            set {
                this.dOC_FUNCIONARIOField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_OBS {
            get {
                return this.dOC_OBSField;
            }
            set {
                this.dOC_OBSField = value;
            }
        }
        
        /// <comentarios/>
        public int DOC_PLAZO {
            get {
                return this.dOC_PLAZOField;
            }
            set {
                this.dOC_PLAZOField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_DATOS_ADIC_REM {
            get {
                return this.dOC_DATOS_ADIC_REMField;
            }
            set {
                this.dOC_DATOS_ADIC_REMField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_DATOS_ADIC_DES {
            get {
                return this.dOC_DATOS_ADIC_DESField;
            }
            set {
                this.dOC_DATOS_ADIC_DESField = value;
            }
        }
        
        /// <comentarios/>
        public int DOC_REFERENCIA_1 {
            get {
                return this.dOC_REFERENCIA_1Field;
            }
            set {
                this.dOC_REFERENCIA_1Field = value;
            }
        }
        
        /// <comentarios/>
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class datosDoctos {
        
        private string iMG_FILE_NAMEField;
        
        private string iMG_SIZEField;
        
        private string iMG_USUARIOField;
        
        private string iMG_FECHAField;
        
        private string iMG_HORAField;
        
        private string iMG_CORRField;
        
        private string iMG_DESCRIPField;
        
        private string dOC_IDENTField;
        
        private string iMG_EXTENSIONField;
        
        private string uRLField;
        
        /// <comentarios/>
        public string IMG_FILE_NAME {
            get {
                return this.iMG_FILE_NAMEField;
            }
            set {
                this.iMG_FILE_NAMEField = value;
            }
        }
        
        /// <comentarios/>
        public string IMG_SIZE {
            get {
                return this.iMG_SIZEField;
            }
            set {
                this.iMG_SIZEField = value;
            }
        }
        
        /// <comentarios/>
        public string IMG_USUARIO {
            get {
                return this.iMG_USUARIOField;
            }
            set {
                this.iMG_USUARIOField = value;
            }
        }
        
        /// <comentarios/>
        public string IMG_FECHA {
            get {
                return this.iMG_FECHAField;
            }
            set {
                this.iMG_FECHAField = value;
            }
        }
        
        /// <comentarios/>
        public string IMG_HORA {
            get {
                return this.iMG_HORAField;
            }
            set {
                this.iMG_HORAField = value;
            }
        }
        
        /// <comentarios/>
        public string IMG_CORR {
            get {
                return this.iMG_CORRField;
            }
            set {
                this.iMG_CORRField = value;
            }
        }
        
        /// <comentarios/>
        public string IMG_DESCRIP {
            get {
                return this.iMG_DESCRIPField;
            }
            set {
                this.iMG_DESCRIPField = value;
            }
        }
        
        /// <comentarios/>
        public string DOC_IDENT {
            get {
                return this.dOC_IDENTField;
            }
            set {
                this.dOC_IDENTField = value;
            }
        }
        
        /// <comentarios/>
        public string IMG_EXTENSION {
            get {
                return this.iMG_EXTENSIONField;
            }
            set {
                this.iMG_EXTENSIONField = value;
            }
        }
        
        /// <comentarios/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void encabezadoDoctosSSDCompletedEventHandler(object sender, encabezadoDoctosSSDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class encabezadoDoctosSSDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal encabezadoDoctosSSDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public encabezadoDoctos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((encabezadoDoctos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void documentosAdjuntosSSDCompletedEventHandler(object sender, documentosAdjuntosSSDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class documentosAdjuntosSSDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal documentosAdjuntosSSDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public datosDoctos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((datosDoctos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void insertarProcesoSSDCompletedEventHandler(object sender, insertarProcesoSSDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarProcesoSSDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarProcesoSSDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ingresarDocto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ingresarDocto[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591